# This is Python code and this is a Python comment

# Run it and then you'll get the following error:

# Traceback (most recent call last):
#   File "main.py", line 11, in <module>
#     print things_to_say[3]
# IndexError: list index out of range

# Pay attention that the Python error tells you what is the line where the error occurs on the second line. And the error that occured is informed on the last thing line of the error message above

# This is a python array. 
things_to_say = ["Hello", "I don't know", "I workeeeeed!"]

# Most of the programming languages have an structure like that that is used to store collections of things, behaving in slightly different ways. You can google "python array" to know more about it.

print (things_to_say[2])

# arrays de python se comportam como os vetores em C, em relação às posições
# o erro dos parenteses o compilador deu o papo. Como eu estou compilando com o python3 no terminal do ubuntu, talvez o resultado do erro seja diferente
